In [3]:
import pandas as pd
from IPython.display import display

# 1. The Historical Data (E-commerce visitors)
data = {
    'minutes_on_site': [1.5, 2.0, 5.5, 8.0, 9.5, 12.0],
    'pages_visited':   [1,   2,   4,   5,   7,   8],
    'bought_product':  [0,   0,   0,   1,   1,   1]  # 0 = No, 1 = Yes
}
df_class = pd.DataFrame(data)

# 2. Splitting into X (Features) and y (Target)
X = df_class[['minutes_on_site', 'pages_visited']] # The behavior we track
y = df_class['bought_product'] # The final action we want to predict

print('--- X (The clues) ---')
display(X)

print('\n--- y (The target) ---')
display(y)

--- X (The clues) ---

   minutes_on_site  pages_visited
0              1.5              1
1              2.0              2
2              5.5              4
3              8.0              5
4              9.5              7
5             12.0              8

--- y (The target) ---

0    0
1    0
2    0
3    1
4    1
5    1
Name: bought_product, dtype: int64

In [6]:
from sklearn.linear_model import LogisticRegression

# 1. Initialize the algorithm
classifier = LogisticRegression()

# 2. Train the model
classifier.fit(X, y)

# 3. Create two brand new, unseen visitors
new_visitors = pd.DataFrame({
    'minutes_on_site': [3.0, 10.0],
    'pages_visited': [2, 6]
})

# 4. Make the predictions
predictions = classifier.predict(new_visitors)

# 5. Peak under the hood at the actual probabilities
probabilities = classifier.predict_proba(new_visitors)

print(f"--- New Visitors DATAFRAME ---")
display(new_visitors)

print(f"Visitor A Prediction: {predictions[0]} (Probability of buying: {probabilities[0][1]*100:.1f}%)")
print(f"Visitor B Prediction: {predictions[1]} (Probability of buying: {probabilities[1][1]*100:.1f}%)")

--- New Visitors DATAFRAME ---

   minutes_on_site  pages_visited
0              3.0              2
1             10.0              6

Visitor A Prediction: 0 (Probability of buying: 2.1%)
Visitor B Prediction: 1 (Probability of buying: 96.1%)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# 1. Generate 100 rendom e-commerce visitors
np.random.seed(42)
minutes = np.random.uniform(1, 15, 100)
pages = np.random.randint(1, 10, 100)

# Simulate logic: Users who spend > 7 mins OR view > 5 pages tend to buy
bought = np.where((minutes > 7) | (pages > 5), 1, 0)

df_large_class = pd.DataFrame({'minutes_on_site': minutes, 'pages_visited': pages, 'bought_product': bought})
X_class = df_large_class[['minutes_on_site', 'pages_visited']]
y_class = df_large_class['bought_product']

# 2. The Train/Test Split (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_class, y_class, test_size=0.2, random_state=42)

# 3. Train the model
model_eval = LogisticRegression()
model_eval.fit(X_train, y_train)

# 4. Predict the 20% vault data
test_preds = model_eval.predict(X_test)

# 5. Evaluate!
accuracy = accuracy_score(y_test, test_preds)
matrix = confusion_matrix(y_test, test_preds)

print(f"Overall Accuracy: {accuracy * 100:.1f}%\n")
print("--- Confusion Matrix ---")
print(matrix)

Overall Accuracy: 90.0%

--- Confusion Matrix ---
[[ 4  0]
 [ 2 14]]

In [10]:
import pandas as pd
from IPython.display import display

# 1. A mini-dataset with a text column
data_text = {
    'user_id': [101, 102, 103, 104],
    'device': ['Mobile', 'Desktop', 'Tablet', 'Mobile'],
    'time_on_site': [5.5, 12.1, 8.0, 3.2]
}
df_text = pd.DataFrame(data_text)

print("--- Original DataFrame (With Text) ---")
display(df_text)

# 2. One-Hot Encoding the 'device' column
# This will automatically turn 'device' into 'device_Desktop', 'device_Mobile', etc.
df_encoded = pd.get_dummies(df_text, columns=['device'], dtype=int)

print("\n--- Encoded DataFrame (Machine Learning Ready!) ---")
display(df_encoded)

--- Original DataFrame (With Text) ---

   user_id   device  time_on_site
0      101   Mobile           5.5
1      102  Desktop          12.1
2      103   Tablet           8.0
3      104   Mobile           3.2

--- Encoded DataFrame (Machine Learning Ready!) ---

   user_id  time_on_site  device_Desktop  device_Mobile  device_Tablet
0      101           5.5               0              1              0
1      102          12.1               1              0              0
2      103           8.0               0              0              1
3      104           3.2               0              1              0